version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - FORCE_HTTPS=true
    networks:
      - proxy_network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    env_file:
      - .env
    networks:
      - proxy_network

networks:
  proxy_network:
    name: proxy_network

volumes:
  certs:
  vhost:
  html:
  acme:
